env:
  es6: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
settings:
  import/external-module-folders:
    - node_modules
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: tsconfig.json
plugins:
  - import
  - unused-imports
extends:
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
rules:
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-vars:
    - error
    - vars: all
      varsIgnorePattern: ^_
      args: after-used
      argsIgnorePattern: ^_
  import/no-cycle: error
  import/newline-after-import: error
  no-restricted-imports:
    - error
    - patterns:
        - ./*
        - ../*
        - '!*.css'
        - '!*.scss'
